name: citysight_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  flutter_svg: ^1.1.1+1
  http: ^0.13.4
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  # mapbox_gl: ^0.16.0
  turf: ^0.0.7
  loadany: ^1.0.0
  cropperx: ^1.1.1
  # file_picker: ^5.0.1
  flutter_inset_box_shadow: ^1.0.7
  dio: ^4.0.6
  fab_circular_menu: ^1.0.2
  date_time_picker: ^2.1.0  
  google_fonts: ^3.0.1
  uuid: ^3.0.6
  flutter_native_splash: ^2.2.10+1
  auto_size_text: ^3.0.0
  skeleton_text: ^3.0.0
  cached_network_image: ^3.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/full_logo.png
    - images/default.jpg
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
